// electron/chrome-host.test.ts
import { describe, it, expect } from 'vitest';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildScript, ensureHostScript, parseClaudeExe, patchScript, readPairing, sharePairing, withPairing } from './chrome-host';

/** El `.bat` real que genera Claude Code, tal cual está en disco. */
const ORIGINAL = [
  '@echo off',
  'REM Chrome native host wrapper script',
  'REM Generated by Claude Code - do not edit manually',
  '"C:\\Users\\WPOSS\\.local\\bin\\claude.exe" --chrome-native-host',
  ''
].join('\r\n');

const CUENTA = 'C:\\Users\\WPOSS\\AppData\\Roaming\\claude-monitor\\profiles\\88eabab9';

const tmp = (prefix: string) => mkdtemp(join(tmpdir(), prefix));

describe('parseClaudeExe', () => {
  it('saca la ruta del ejecutable del .bat que genera Claude Code', () => {
    expect(parseClaudeExe(ORIGINAL)).toBe('C:\\Users\\WPOSS\\.local\\bin\\claude.exe');
  });

  it('devuelve null si el .bat no es el que se espera, para no inventar una ruta', () => {
    expect(parseClaudeExe('@echo off\r\nexit /b 0')).toBeNull();
  });
});

describe('patchScript', () => {
  it('fija la cuenta antes de arrancar el puente: es el arreglo entero', () => {
    const lineas = patchScript(ORIGINAL, CUENTA)!.split('\r\n');
    const set = lineas.findIndex((l) => l === `set "CLAUDE_CONFIG_DIR=${CUENTA}"`);
    const run = lineas.findIndex((l) => l.includes('--chrome-native-host'));
    expect(set).toBeGreaterThan(-1);
    expect(run).toBeGreaterThan(set);
  });

  it('conserva las barras invertidas: cmd no las come, a diferencia de wt.exe', () => {
    expect(patchScript(ORIGINAL, 'C:\\a\\b')).toContain('C:\\a\\b');
  });

  it('no imprime nada: cualquier eco corrompe el protocolo por stdout', () => {
    const bat = patchScript(ORIGINAL, CUENTA)!;
    expect(bat.startsWith('@echo off')).toBe(true);
    expect(bat).not.toMatch(/^\s*echo /m);
  });

  it('es idempotente: parchar dos veces no duplica la línea', () => {
    const unaVez = patchScript(ORIGINAL, CUENTA)!;
    expect(patchScript(unaVez, CUENTA)).toBeNull();
  });

  it('si la cuenta cambió de carpeta, reemplaza el valor viejo en vez de sumar otro', () => {
    const viejo = patchScript(ORIGINAL, 'C:\\vieja')!;
    const nuevo = patchScript(viejo, 'C:\\nueva')!;
    expect(nuevo.match(/set "CLAUDE_CONFIG_DIR=/g)).toHaveLength(1);
    expect(nuevo).toContain('C:\\nueva');
    expect(nuevo).not.toContain('C:\\vieja');
  });

  it('deja en paz un .bat que no arranca el puente, en vez de escribir cualquier cosa', () => {
    expect(patchScript('@echo off\r\nexit /b 0\r\n', CUENTA)).toBeNull();
  });
});

describe('buildScript', () => {
  it('lo que arma es parchable y ya viene con la cuenta', () => {
    const bat = buildScript(CUENTA, 'C:\\bin\\claude.exe');
    expect(parseClaudeExe(bat)).toBe('C:\\bin\\claude.exe');
    expect(patchScript(bat, CUENTA)).toBeNull();
  });
});

describe('ensureHostScript', () => {
  it('parcha el .bat de Claude Code y guarda el original al lado', async () => {
    const cuenta = await tmp('cm-cuenta-');
    try {
      const script = join(cuenta, 'chrome', 'chrome-native-host.bat');
      await mkdir(join(cuenta, 'chrome'), { recursive: true });
      await writeFile(script, ORIGINAL);

      expect(await ensureHostScript(cuenta)).toBe(true);
      expect(await readFile(script, 'utf8')).toContain(`set "CLAUDE_CONFIG_DIR=${cuenta}"`);
      expect(await readFile(`${script}.bak-claude-monitor`, 'utf8')).toBe(ORIGINAL);

      // Segunda pasada: ya está bien, no hay nada que escribir.
      expect(await ensureHostScript(cuenta)).toBe(false);
    } finally {
      await rm(cuenta, { recursive: true, force: true });
    }
  });

  it('a una cuenta nueva le crea el .bat, sacando el ejecutable del pozo', async () => {
    const pozo = await tmp('cm-pozo-');
    const cuenta = await tmp('cm-cuenta-');
    try {
      await mkdir(join(pozo, 'chrome'), { recursive: true });
      await writeFile(join(pozo, 'chrome', 'chrome-native-host.bat'), ORIGINAL);

      expect(await ensureHostScript(cuenta, pozo)).toBe(true);
      const bat = await readFile(join(cuenta, 'chrome', 'chrome-native-host.bat'), 'utf8');
      expect(bat).toContain(`set "CLAUDE_CONFIG_DIR=${cuenta}"`);
      expect(parseClaudeExe(bat)).toBe('C:\\Users\\WPOSS\\.local\\bin\\claude.exe');
    } finally {
      await rm(pozo, { recursive: true, force: true });
      await rm(cuenta, { recursive: true, force: true });
    }
  });

  it('sin saber dónde está claude.exe no escribe nada', async () => {
    const cuenta = await tmp('cm-cuenta-');
    try {
      expect(await ensureHostScript(cuenta)).toBe(false);
    } finally {
      await rm(cuenta, { recursive: true, force: true });
    }
  });
});

const PAREJA = { pairedDeviceId: '7ef9c3cc', pairedDeviceName: 'Browser 1' };
const EMPAREJADO = JSON.stringify({ numStartups: 4, chromeExtension: PAREJA });

describe('readPairing', () => {
  it('lo encuentra en ~/.claude.json, AL LADO de la carpeta y no adentro', async () => {
    const casa = await tmp('cm-casa-');
    try {
      await mkdir(join(casa, '.claude'), { recursive: true });
      await writeFile(join(casa, '.claude.json'), EMPAREJADO);
      expect(await readPairing(join(casa, '.claude'))).toEqual(PAREJA);
    } finally {
      await rm(casa, { recursive: true, force: true });
    }
  });

  it('gana el que TIENE emparejamiento, no el primero que aparece', async () => {
    // El caso real: existen los dos .claude.json y sólo el de afuera está emparejado.
    const casa = await tmp('cm-casa-');
    const pozo = join(casa, '.claude');
    try {
      await mkdir(pozo, { recursive: true });
      await writeFile(join(casa, '.claude.json'), EMPAREJADO);
      await writeFile(join(pozo, '.claude.json'), '{"numStartups":9}');
      expect(await readPairing(pozo)).toEqual(PAREJA);
    } finally {
      await rm(casa, { recursive: true, force: true });
    }
  });

  it('sin emparejamiento en ningún lado devuelve null, en vez de inventar uno', async () => {
    const pozo = await tmp('cm-pozo-');
    try {
      await writeFile(join(pozo, '.claude.json'), '{"numStartups":1}');
      expect(await readPairing(pozo)).toBeNull();
    } finally {
      await rm(pozo, { recursive: true, force: true });
    }
  });
});

describe('withPairing', () => {
  it('le pone a la cuenta el emparejamiento que este Chrome ya hizo', () => {
    const salida = JSON.parse(withPairing(PAREJA, '{"numStartups":1}')!);
    expect(salida.chromeExtension).toEqual(PAREJA);
    expect(salida.numStartups).toBe(1);
  });

  it('no toca el resto del archivo, que tiene 40 KB de estado de la cuenta', () => {
    const propio = JSON.stringify({ tipsHistory: { a: 1 }, oauthAccount: { emailAddress: 'yo@x.com' } });
    const salida = JSON.parse(withPairing(PAREJA, propio)!);
    expect(salida.oauthAccount.emailAddress).toBe('yo@x.com');
    expect(salida.tipsHistory).toEqual({ a: 1 });
  });

  it('respeta el emparejamiento propio: pisarlo la desconectaría de su navegador', () => {
    const propio = JSON.stringify({ chromeExtension: { pairedDeviceId: 'otro' } });
    expect(withPairing(PAREJA, propio)).toBeNull();
  });
});

describe('sharePairing', () => {
  it('escribe el emparejamiento en la cuenta', async () => {
    const cuenta = await tmp('cm-cuenta-');
    try {
      await writeFile(join(cuenta, '.claude.json'), '{"numStartups":1}');
      expect(await sharePairing(cuenta, PAREJA)).toBe(true);
      const o = JSON.parse(await readFile(join(cuenta, '.claude.json'), 'utf8'));
      expect(o.chromeExtension).toEqual(PAREJA);
    } finally {
      await rm(cuenta, { recursive: true, force: true });
    }
  });

  it('un .claude.json corrupto no se sobreescribe con nada', async () => {
    const cuenta = await tmp('cm-cuenta-');
    try {
      await writeFile(join(cuenta, '.claude.json'), 'esto no es json');
      expect(await sharePairing(cuenta, PAREJA)).toBe(false);
      expect(await readFile(join(cuenta, '.claude.json'), 'utf8')).toBe('esto no es json');
    } finally {
      await rm(cuenta, { recursive: true, force: true });
    }
  });
});
