// electron/chrome-host.test.ts
import { describe, it, expect } from 'vitest';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildScript, ensureAll, ensureHostScript, parseClaudeExe, patchScript } from './chrome-host';
import type { Profile } from '../shared/types';

/** El `.bat` real que genera Claude Code, tal cual está en disco. */
const ORIGINAL = [
  '@echo off',
  'REM Chrome native host wrapper script',
  'REM Generated by Claude Code - do not edit manually',
  '"C:\\Users\\WPOSS\\.local\\bin\\claude.exe" --chrome-native-host',
  ''
].join('\r\n');

const CUENTA = 'C:\\Users\\WPOSS\\AppData\\Roaming\\claude-monitor\\profiles\\88eabab9';

const tmp = (prefix: string) => mkdtemp(join(tmpdir(), prefix));

describe('parseClaudeExe', () => {
  it('saca la ruta del ejecutable del .bat que genera Claude Code', () => {
    expect(parseClaudeExe(ORIGINAL)).toBe('C:\\Users\\WPOSS\\.local\\bin\\claude.exe');
  });

  it('devuelve null si el .bat no es el que se espera, para no inventar una ruta', () => {
    expect(parseClaudeExe('@echo off\r\nexit /b 0')).toBeNull();
  });
});

describe('patchScript', () => {
  it('fija la cuenta antes de arrancar el puente: es el arreglo entero', () => {
    const lineas = patchScript(ORIGINAL, CUENTA)!.split('\r\n');
    const set = lineas.findIndex((l) => l === `set "CLAUDE_CONFIG_DIR=${CUENTA}"`);
    const run = lineas.findIndex((l) => l.includes('--chrome-native-host'));
    expect(set).toBeGreaterThan(-1);
    expect(run).toBeGreaterThan(set);
  });

  it('conserva las barras invertidas: cmd no las come, a diferencia de wt.exe', () => {
    expect(patchScript(ORIGINAL, 'C:\\a\\b')).toContain('C:\\a\\b');
  });

  it('no imprime nada: cualquier eco corrompe el protocolo por stdout', () => {
    const bat = patchScript(ORIGINAL, CUENTA)!;
    expect(bat.startsWith('@echo off')).toBe(true);
    expect(bat).not.toMatch(/^\s*echo /m);
  });

  it('es idempotente: parchar dos veces no duplica la línea', () => {
    const unaVez = patchScript(ORIGINAL, CUENTA)!;
    expect(patchScript(unaVez, CUENTA)).toBeNull();
  });

  it('si la cuenta cambió de carpeta, reemplaza el valor viejo en vez de sumar otro', () => {
    const viejo = patchScript(ORIGINAL, 'C:\\vieja')!;
    const nuevo = patchScript(viejo, 'C:\\nueva')!;
    expect(nuevo.match(/set "CLAUDE_CONFIG_DIR=/g)).toHaveLength(1);
    expect(nuevo).toContain('C:\\nueva');
    expect(nuevo).not.toContain('C:\\vieja');
  });

  it('deja en paz un .bat que no arranca el puente, en vez de escribir cualquier cosa', () => {
    expect(patchScript('@echo off\r\nexit /b 0\r\n', CUENTA)).toBeNull();
  });
});

describe('buildScript', () => {
  it('lo que arma es parchable y ya viene con la cuenta', () => {
    const bat = buildScript(CUENTA, 'C:\\bin\\claude.exe');
    expect(parseClaudeExe(bat)).toBe('C:\\bin\\claude.exe');
    expect(patchScript(bat, CUENTA)).toBeNull();
  });
});

describe('ensureHostScript', () => {
  it('parcha el .bat de Claude Code y guarda el original al lado', async () => {
    const cuenta = await tmp('cm-cuenta-');
    try {
      const script = join(cuenta, 'chrome', 'chrome-native-host.bat');
      await mkdir(join(cuenta, 'chrome'), { recursive: true });
      await writeFile(script, ORIGINAL);

      expect(await ensureHostScript(cuenta)).toBe(true);
      expect(await readFile(script, 'utf8')).toContain(`set "CLAUDE_CONFIG_DIR=${cuenta}"`);
      expect(await readFile(`${script}.bak-claude-monitor`, 'utf8')).toBe(ORIGINAL);

      // Segunda pasada: ya está bien, no hay nada que escribir.
      expect(await ensureHostScript(cuenta)).toBe(false);
    } finally {
      await rm(cuenta, { recursive: true, force: true });
    }
  });

  it('a una cuenta nueva le crea el .bat, sacando el ejecutable del pozo', async () => {
    const pozo = await tmp('cm-pozo-');
    const cuenta = await tmp('cm-cuenta-');
    try {
      await mkdir(join(pozo, 'chrome'), { recursive: true });
      await writeFile(join(pozo, 'chrome', 'chrome-native-host.bat'), ORIGINAL);

      expect(await ensureHostScript(cuenta, pozo)).toBe(true);
      const bat = await readFile(join(cuenta, 'chrome', 'chrome-native-host.bat'), 'utf8');
      expect(bat).toContain(`set "CLAUDE_CONFIG_DIR=${cuenta}"`);
      expect(parseClaudeExe(bat)).toBe('C:\\Users\\WPOSS\\.local\\bin\\claude.exe');
    } finally {
      await rm(pozo, { recursive: true, force: true });
      await rm(cuenta, { recursive: true, force: true });
    }
  });

  it('sin saber dónde está claude.exe no escribe nada', async () => {
    const cuenta = await tmp('cm-cuenta-');
    try {
      expect(await ensureHostScript(cuenta)).toBe(false);
    } finally {
      await rm(cuenta, { recursive: true, force: true });
    }
  });
});

describe('ensureAll', () => {
  it('parcha el puente de la cuenta Windows y no toca la cuenta WSL', async () => {
    const pozo = await tmp('cm-pozo-');
    const cuentaWindows = await tmp('cm-cuenta-win-');
    // Directorio temporal cualquiera: representa el configDir de una cuenta
    // WSL sin usar ninguna UNC ni ninguna distro real.
    const cuentaWsl = await tmp('cm-cuenta-wsl-');
    try {
      await mkdir(join(cuentaWindows, 'chrome'), { recursive: true });
      await writeFile(join(cuentaWindows, 'chrome', 'chrome-native-host.bat'), ORIGINAL);
      await mkdir(join(cuentaWsl, 'chrome'), { recursive: true });
      await writeFile(join(cuentaWsl, 'chrome', 'chrome-native-host.bat'), ORIGINAL);

      const perfiles: Profile[] = [
        { id: 'w1', name: 'Windows', configDir: cuentaWindows, isDefault: false, entorno: { tipo: 'windows' } },
        {
          id: 'u1',
          name: 'Ubuntu',
          configDir: cuentaWsl,
          isDefault: false,
          entorno: { tipo: 'wsl', distro: 'Ubuntu', home: '/home/vos' }
        }
      ];

      await ensureAll(perfiles, pozo);

      expect(await readFile(join(cuentaWindows, 'chrome', 'chrome-native-host.bat'), 'utf8')).toContain(
        `set "CLAUDE_CONFIG_DIR=${cuentaWindows}"`
      );
      // La cuenta WSL no se tocó: su .bat sigue siendo el original, sin parchar.
      expect(await readFile(join(cuentaWsl, 'chrome', 'chrome-native-host.bat'), 'utf8')).toBe(ORIGINAL);
      await expect(readFile(`${join(cuentaWsl, 'chrome', 'chrome-native-host.bat')}.bak-claude-monitor`, 'utf8')).rejects.toThrow();
    } finally {
      await rm(pozo, { recursive: true, force: true });
      await rm(cuentaWindows, { recursive: true, force: true });
      await rm(cuentaWsl, { recursive: true, force: true });
    }
  });
});

