// electron/transcript.test.ts
import { describe, it, expect } from 'vitest';
import { parseTranscriptLines } from './transcript';

const linea = (o: unknown) => JSON.stringify(o);

const usuario = (content: unknown, extra: Record<string, unknown> = {}) =>
  linea({ type: 'user', cwd: 'C:/proyecto', timestamp: '2026-08-14T12:00:00Z', message: { content }, ...extra });

const asistente = (content: unknown, extra: Record<string, unknown> = {}) =>
  linea({ type: 'assistant', timestamp: '2026-08-14T12:00:01Z', message: { content }, ...extra });

describe('parseTranscriptLines', () => {
  it('arma la conversación en orden y cuenta las herramientas de cada turno', () => {
    const t = parseTranscriptLines([
      usuario('arregla el login'),
      asistente([
        { type: 'thinking', text: 'no se muestra' },
        { type: 'text', text: 'Voy a mirarlo.' },
        { type: 'tool_use', name: 'Read' },
        { type: 'tool_use', name: 'Edit' }
      ]),
      usuario([{ type: 'tool_result', content: 'ok' }]), // devolución de herramienta
      asistente([{ type: 'text', text: 'Listo.' }])
    ]);

    expect(t.cwd).toBe('C:/proyecto');
    expect(t.truncated).toBe(false);
    expect(t.messages).toEqual([
      { role: 'user', text: 'arregla el login', tools: 0, timestamp: '2026-08-14T12:00:00Z' },
      { role: 'assistant', text: 'Voy a mirarlo.', tools: 2, timestamp: '2026-08-14T12:00:01Z' },
      { role: 'assistant', text: 'Listo.', tools: 0, timestamp: '2026-08-14T12:00:01Z' }
    ]);
  });

  it('conserva el turno que sólo usó herramientas: sin él quedaría un hueco', () => {
    const t = parseTranscriptLines([asistente([{ type: 'tool_use', name: 'Bash' }])]);
    expect(t.messages).toHaveLength(1);
    expect(t.messages[0]).toMatchObject({ role: 'assistant', text: '', tools: 1 });
  });

  it('descarta subagentes, meta, slash commands y líneas rotas', () => {
    const t = parseTranscriptLines([
      'no es json',
      '',
      usuario('<command-message>caveman</command-message>'),
      usuario('Caveat: The messages below were generated by the user while running local commands.'),
      usuario('mensaje de un subagente', { isSidechain: true }),
      usuario('linea meta', { isMeta: true }),
      usuario('esto sí se dijo')
    ]);
    expect(t.messages.map((m) => m.text)).toEqual(['esto sí se dijo']);
  });

  it('acepta contenido como string suelto', () => {
    expect(parseTranscriptLines([usuario('hola')]).messages[0].text).toBe('hola');
  });
});
