// electron/transcript.test.ts
import { describe, it, expect } from 'vitest';
import { parseTranscriptLines, reescribirCwd } from './transcript';

const linea = (o: unknown) => JSON.stringify(o);

const usuario = (content: unknown, extra: Record<string, unknown> = {}) =>
  linea({ type: 'user', cwd: 'C:/proyecto', timestamp: '2026-08-14T12:00:00Z', message: { content }, ...extra });

const asistente = (content: unknown, extra: Record<string, unknown> = {}) =>
  linea({ type: 'assistant', timestamp: '2026-08-14T12:00:01Z', message: { content }, ...extra });

describe('parseTranscriptLines', () => {
  it('arma la conversación en orden y cuenta las herramientas de cada turno', () => {
    const t = parseTranscriptLines([
      usuario('arregla el login'),
      asistente([
        { type: 'thinking', text: 'no se muestra' },
        { type: 'text', text: 'Voy a mirarlo.' },
        { type: 'tool_use', name: 'Read' },
        { type: 'tool_use', name: 'Edit' }
      ]),
      usuario([{ type: 'tool_result', content: 'ok' }]), // devolución de herramienta
      asistente([{ type: 'text', text: 'Listo.' }])
    ]);

    expect(t.cwd).toBe('C:/proyecto');
    expect(t.truncated).toBe(false);
    expect(t.messages).toEqual([
      { role: 'user', text: 'arregla el login', tools: 0, timestamp: '2026-08-14T12:00:00Z' },
      { role: 'assistant', text: 'Voy a mirarlo.', tools: 2, timestamp: '2026-08-14T12:00:01Z' },
      { role: 'assistant', text: 'Listo.', tools: 0, timestamp: '2026-08-14T12:00:01Z' }
    ]);
  });

  it('conserva el turno que sólo usó herramientas: sin él quedaría un hueco', () => {
    const t = parseTranscriptLines([asistente([{ type: 'tool_use', name: 'Bash' }])]);
    expect(t.messages).toHaveLength(1);
    expect(t.messages[0]).toMatchObject({ role: 'assistant', text: '', tools: 1 });
  });

  it('descarta subagentes, meta, slash commands y líneas rotas', () => {
    const t = parseTranscriptLines([
      'no es json',
      '',
      usuario('<command-message>caveman</command-message>'),
      usuario('Caveat: The messages below were generated by the user while running local commands.'),
      usuario('mensaje de un subagente', { isSidechain: true }),
      usuario('linea meta', { isMeta: true }),
      usuario('esto sí se dijo')
    ]);
    expect(t.messages.map((m) => m.text)).toEqual(['esto sí se dijo']);
  });

  it('acepta contenido como string suelto', () => {
    expect(parseTranscriptLines([usuario('hola')]).messages[0].text).toBe('hola');
  });
});

describe('reescribirCwd', () => {
  const posix = '/home/pablorm/Proyectos/wposs/new6260';
  const unc = '\\wsl.localhost\Ubuntu\home\pablorm\Proyectos\wposs\new6260';

  it('cambia el valor de la clave cwd', () => {
    const linea = `{"type":"user","cwd":"${posix}","message":{"content":"hola"}}`;
    const salida = reescribirCwd(linea, posix, unc);
    expect(JSON.parse(salida).cwd).toBe(unc);
  });

  it('lo cambia en TODAS las líneas: el cwd va en cada entrada', () => {
    const doc = [
      `{"cwd":"${posix}","type":"user"}`,
      `{"cwd":"${posix}","type":"assistant"}`
    ].join(String.fromCharCode(10));
    const salida = reescribirCwd(doc, posix, unc);
    expect(salida.split(String.fromCharCode(10)).every((l) => JSON.parse(l).cwd === unc)).toBe(true);
  });

  // Lo que NO tiene que pasar: si alguien pegó la ruta adentro de un mensaje,
  // cambiarla ahí sería reescribir lo que se dijo.
  it('no toca la ruta cuando aparece adentro de un mensaje', () => {
    const linea = `{"cwd":"${posix}","message":{"content":"corré esto en ${posix} y avisá"}}`;
    const salida = reescribirCwd(linea, posix, unc);
    const entrada = JSON.parse(salida);
    expect(entrada.cwd).toBe(unc);
    expect(entrada.message.content).toContain(posix);
  });

  it('aguanta el espaciado del JSON con formato', () => {
    const linea = `{"cwd" : "${posix}"}`;
    expect(JSON.parse(reescribirCwd(linea, posix, unc)).cwd).toBe(unc);
  });

  it('es idempotente: pasarlo dos veces no rompe nada', () => {
    const linea = `{"cwd":"${posix}"}`;
    const una = reescribirCwd(linea, posix, unc);
    expect(reescribirCwd(una, posix, unc)).toBe(una);
  });

  it('no toca un transcript de otra carpeta', () => {
    const linea = `{"cwd":"/home/otro/proyecto"}`;
    expect(reescribirCwd(linea, posix, unc)).toBe(linea);
  });
});
